Repository atlp-rwanda/matadors-rn-medica, pull requests merged in 2024-07, with the labels that each got.

#188 Fix: App start popup error about children without keys
  app/(app)/_layout.tsx
Labels: Fix

#191 Feature: Appointments Intergration
  app/(app)/ActionMenu/Booking/Select-package.tsx
  app/(app)/Appointments/MessagingAppointment/index.tsx
  app/(app)/Appointments/Review/ReviewBlankform.tsx
  app/(app)/Appointments/VideoCallAppointment/index.tsx
  app/(app)/Appointments/VoiceCallAppointment/index.tsx
  app/(app)/Appointments/index.tsx
  assets/images/noappointments.png
  assets/images/noappointmentsdark.png
  components/AppointmentDoctorsCards.tsx
  components/Appointmentnotfound.tsx
  components/DoctorCard.tsx
  constants/Types.ts
Labels: Feature

#197 Feature: Implement Chat Room Scheduling and Messaging Feature using Stream.io
  app.json
  app/(app)/ActionMenu/Booking/EnterYourPin.tsx
  app/(app)/ActionMenu/index.tsx
  app/(app)/Appointments/MessagingAppointment/Camera.tsx
  app/(app)/Appointments/MessagingAppointment/ChannelList.tsx
  app/(app)/Appointments/MessagingAppointment/ChannelScreen.tsx
  app/(app)/Appointments/MessagingAppointment/ChatMessaging.tsx
  app/(app)/Appointments/MessagingAppointment/Home.tsx
  app/(app)/Appointments/MessagingAppointment/_layout.tsx
  app/(app)/Appointments/MessagingAppointment/index.tsx
  app/(app)/Profile/index.tsx
  constants/Types.ts
  ctx/ChatContext.tsx
  package-lock.json
  package.json
  utils/LoggedInUser.ts
Labels: Need Review

#208 Feature: Implemented the cancel appointment.
  app/(app)/ActionMenu/index.tsx
  app/(app)/Appointments/CancelAppointment/cancelreason.tsx
  app/(app)/Appointments/CancelAppointment/index.tsx
  app/(app)/Appointments/_layout.tsx
  app/(app)/Appointments/index.tsx
  app/Appointments.json
  components/AppointmentDoctorsCards.tsx
  components/cancelappointmentmodal.tsx
Labels: Need Review

#207 Refine Appointment Booking: Add Form Validation and Duration-Based Amount Calculation
  app/(app)/ActionMenu/AllDoctorScreen.tsx
  app/(app)/ActionMenu/Booking/BookingAppointment.tsx
  app/(app)/ActionMenu/Booking/EnterYourPin.tsx
  app/(app)/ActionMenu/Booking/Patient-details.tsx
  app/(app)/ActionMenu/Booking/Select-package.tsx
  app/(app)/ActionMenu/Booking/SelectPayment.tsx
  app/(app)/ActionMenu/Booking/reviewSummary.tsx
  app/(app)/ActionMenu/FavoriteDoctorScreen.tsx
  assets/icons/left.ts
  components/HeaderComponent.tsx
  components/UI/DatePicker.tsx
  components/UI/DropDown.tsx
  components/UI/Input.tsx
Labels: Fix, Need Review

#209 Fix: updating user profile picture and email
  app/(app)/ActionMenu/index.tsx
  app/(app)/Profile/EditProfile.tsx
  app/(app)/Profile/index.tsx
  utils/LoggedInUser.ts
Labels: Fix, Need Review

#211 Implement Doctor's ratings and review feature
  app/(app)/ActionMenu/AllDoctorScreen.tsx
  app/(app)/ActionMenu/Booking/DoctorRatingAndReview.tsx
  app/(app)/ActionMenu/Booking/Doctor_details.tsx
  app/(app)/ActionMenu/index.tsx
  app/(app)/Appointments/Review/ReviewBlankform.tsx
  app/(app)/Appointments/index.tsx
  components/DoctorComponent.tsx
  components/ReviewerCardComponent.tsx
Labels: Feature, Need Review

#214 feature: filter doctors using icons on the home screen
  app/(app)/ActionMenu/index.tsx
  assets/images/Dentist.png
  assets/images/GeneralDoctor.png
  assets/images/More.png
  assets/images/Neurologist.png
  assets/images/Nutritionist.png
  assets/images/Optician.png
  assets/images/Pediatric.png
  assets/images/Radiologist.png
  constants/icon.ts
Labels: Need Review

#218 Implement Date Availability Check for Appointment Bookings in Medica App
  app/(app)/ActionMenu/Booking/BookingAppointment.tsx
  components/SelectHour.tsx
  components/UI/DatePicker.tsx
Labels: Need Review

#212 Fix: fixed popup errors on app startup, and in profile section
  app/(app)/ActionMenu/index.tsx
  app/(app)/_layout.tsx
  components/UI/Tags/index.tsx
  eas.json
  package-lock.json
  package.json
Labels: Fix

#221 Integrate Flutterwave Payment Method in Medica App
  app/(app)/ActionMenu/Booking/Patient-details.tsx
  app/(app)/ActionMenu/Booking/Select-package.tsx
  app/(app)/ActionMenu/Booking/SelectPayment.tsx
  app/(app)/ActionMenu/Booking/SelectPaymentFlutter.tsx
  app/(app)/ActionMenu/Booking/_layout.tsx
  app/(app)/ActionMenu/Booking/reviewSummary.tsx
  app/(app)/ActionMenu/index.tsx
  components/Profile/SelectedPaymentCardListing.tsx
  components/UI/Icons.tsx
  package-lock.json
  package.json
Labels: Feature, Need Review

#222 Implement Audio Call Feature for Patients
  api.ts
  app.json
  app/(app)/Appointments/Review/ReviewBlankform.tsx
  app/(app)/Appointments/VideoCallAppointment/VideoCallRinging.tsx
  app/(app)/Appointments/VoiceCallAppointment/MyAppointmentVoiceCall.tsx
  app/(app)/Appointments/VoiceCallAppointment/SessionEnded.tsx
  app/(app)/Appointments/VoiceCallAppointment/VoiceCall.tsx
  app/(app)/Appointments/VoiceCallAppointment/VoiceCallRinging.tsx
  app/(app)/Appointments/VoiceCallAppointment/index.tsx
  app/(app)/Appointments/_layout.tsx
  app/(app)/Appointments/index.tsx
  app/(app)/Profile/index.tsx
  assets/images/Completed.png
  components/Icons/Icons.ts
  package-lock.json
  package.json
Labels: Feature, Need Review
