Repository atlp-rwanda/matadors-rn-medica, pull requests merged in 2024-06, with the labels that each got.

#122 bug fix: provide dark theme to all screens .
  app/(app)/ActionMenu/Booking/AddNewCard.tsx
  app/(app)/ActionMenu/Booking/BookingAppointment.tsx
  app/(app)/ActionMenu/Booking/DoctorRatingAndReview.tsx
  app/(app)/ActionMenu/Booking/Doctor_details.tsx
  app/(app)/ActionMenu/Booking/EnterYourPin.tsx
  app/(app)/ActionMenu/Booking/Patient-details.tsx
  app/(app)/ActionMenu/Booking/QRCodeScanner.tsx
  app/(app)/ActionMenu/Booking/Select-package.tsx
  app/(app)/ActionMenu/Booking/SelectPayment.tsx
  app/(app)/ActionMenu/Booking/_layout.tsx
  app/(app)/ActionMenu/Booking/reviewSummary.tsx
  app/(app)/ActionMenu/FavoriteDoctorScreen.tsx
  app/(app)/ActionMenu/index.tsx
  app/(app)/Profile/index.tsx
  app/(app)/index.tsx
  app/(auth)/SignIn&SignOut/LetsYouIn.tsx
  app/(auth)/SignIn&SignOut/SetYourFingerPrint.tsx
  app/(auth)/SignIn&SignOut/SignInBlankForm.tsx
  app/(auth)/SignIn&SignOut/SignUpBlankForm.tsx
  app/(auth)/_layout.tsx
  app/_layout.tsx
  assets/icons/LeftArrowWhite.ts
  assets/icons/MoreWhite.ts
  assets/icons/SearchWhiteIcon.ts
  assets/images/Booking/Card.ts
  assets/images/Mocard.png
  components/DoctorComponent.tsx
  components/HeaderComponent.tsx
  components/Icons/Amazon.png
  components/Icons/BlueCard.png
  components/Icons/GreyDownArrow.svg
  components/Icons/GreyScanner.svg
  components/Icons/GreyTimer.svg
  components/Icons/Icons.ts
  components/Icons/Mocard.svg
  components/Icons/TwoEllipse.png
  components/Icons/WhiteDownArrow.svg
  components/Icons/WhiteScanner.svg
  components/Icons/WhiteTimer.svg
  components/UI/Header.tsx
  components/UI/icons/Heart.svg
  components/UI/icons/SessionEnded.tsx
  components/UI/icons/WhiteHeart.ts
  components/UI/icons/WhiteMoreCircle.svg
  constants/icon.ts
  package-lock.json
Labels: Need Review

#121 fix: book and reschedule appointment screen
  app/(app)/ActionMenu/Booking/BookingAppointment.tsx
  app/(app)/ActionMenu/Booking/Doctor_details.tsx
  app/(app)/Appointments/ReschedualAppointment/Selectreason.tsx
  app/(app)/Appointments/ReschedualAppointment/rescheduleDate.tsx
Labels: Fix, Need Review

#120 Enhance favorite Doctor Screen and add Dark theme
  app/(app)/ActionMenu/FavoriteDoctorScreen.tsx
  app/(app)/Appointments/MessagingAppointment/index.tsx
  components/DoctorComponent.tsx
  components/FilterSearchComponent.tsx
  components/FoundDoctorCount.tsx
  components/HeaderComponent.tsx
  components/Icons/Icons.ts
  components/NofoundComponent.tsx
  components/Profile/ContactsListing.tsx
  components/Ratebtn.tsx
  components/RemovefavoritePopup.tsx
  components/SearchComponent.tsx
  package-lock.json
Labels: Need Review

#130 Set Up Supabase Backend and Email Authentication for Medica Project
  app.json
  app/(auth)/SignIn&SignOut/LetsYouIn.tsx
  app/(auth)/SignIn&SignOut/SignInBlankForm.tsx
  app/(auth)/SignIn&SignOut/SignUpBlankForm.tsx
  lib/supabase.ts
  package-lock.json
  package.json
Labels: Chore, Need Review

#131 Configure GitHub Actions for Automated iOS and Android Builds on Merge to Main
  .github/workflows/update.yml
  app.json
  eas.json
  package.json
Labels: Need Review

#136 Refactor: Reusable components
  app/(app)/ActionMenu/Booking/BookingAppointment.tsx
  app/(app)/ActionMenu/Booking/DoctorRatingAndReview.tsx
  app/(app)/ActionMenu/Booking/Doctor_details.tsx
  app/(app)/ActionMenu/Booking/EnterYourPin.tsx
  app/(app)/ActionMenu/Booking/Patient-details.tsx
  app/(app)/ActionMenu/Booking/Select-package.tsx
  app/(app)/ActionMenu/Booking/SelectPayment.tsx
  app/(app)/ActionMenu/Booking/_layout.tsx
  app/(app)/ActionMenu/Booking/reviewSummary.tsx
  app/(app)/ActionMenu/FavoriteDoctorScreen.tsx
  app/(app)/ActionMenu/_layout.tsx
  app/(app)/ActionMenu/index.tsx
  app/(app)/Appointments/ReschedualAppointment/rescheduleDate.tsx
  app/(app)/Appointments/VideoCallAppointment/VideoCall.tsx
  app/(app)/Profile/EditProfile.tsx
  app/(app)/Profile/HelpCenter/FAQ.tsx
  app/(app)/Profile/index.tsx
  app/(app)/index.tsx
  app/(auth)/CreateNewPassword.tsx
  app/(auth)/SignIn&SignOut/Create-NewPin.tsx
  app/(auth)/SignIn&SignOut/LetsYouIn.tsx
  app/(auth)/SignIn&SignOut/SetYourFingerPrint.tsx
  app/(auth)/SignIn&SignOut/SignInBlankForm.tsx
  app/(auth)/SignIn&SignOut/YourProfile.tsx
  app/(auth)/_layout.tsx
  app/_layout.tsx
  app/index.tsx
  app/onBoarding/index.tsx
  app/spinner/Loading.tsx
  assets/icons/EmptyImageContainer.ts
  assets/images/doctorImage.png
  assets/images/profileImage.png
  components/FilterSearchComponent.tsx
  components/PackagesContainer.tsx
  components/Profile/FriendsListing.tsx
  components/Profile/OptionListing.tsx
  components/RemovefavoritePopup.tsx
  components/ReviewerCardComponent.tsx
  components/UI/Button.tsx
  components/UI/ChipsComponent.tsx
  components/UI/CustomDropdown.tsx
  components/UI/DatePicker.tsx
  components/UI/DropDown.tsx
  components/UI/Header.tsx
  components/UI/Input.tsx
  components/UI/PackageItem.tsx
  components/UI/PaymentChooseContainer/PaymentChooseInputCard.tsx
  components/UI/SelectProfile.tsx
  components/UI/Tags/Tag.tsx
  components/UI/Tags/index.tsx
  components/UI/TextArea.tsx
  constants/icon.ts
  ctx/AuthContext.tsx
  lib/supabase.ts
  package-lock.json
  package.json
Labels: Need Review

#149 Facebook Login Integration in Medica App
  app.json
  app/(auth)/SignIn&SignOut/LetsYouIn.tsx
  app/(auth)/SignIn&SignOut/SignInBlankForm.tsx
  app/(auth)/SignIn&SignOut/SignUpBlankForm.tsx
  components/UI/CustomTabBarIcon.tsx
  package-lock.json
  package.json
Labels: Feature, Need Review

#155 Refactor: Reusable alert component
  app/(auth)/SignIn&SignOut/SignInBlankForm.tsx
  app/(auth)/SignIn&SignOut/SignUpBlankForm.tsx
  components/UI/AlertComponent.tsx
  components/UI/Alerts.tsx
  constants/icon.ts
Labels: Need Review

#160 Feature: Implement Email Value Passing in Reset Password Flow
  app/(auth)/CreateNewPassword.tsx
  app/(auth)/ForgotPassword&Reset/OTPform.tsx
  app/(auth)/ForgotPassword&Reset/[OTPform].tsx
  app/(auth)/ForgotPassword&Reset/index.tsx
  app/(auth)/SignIn&SignOut/SignInBlankForm.tsx
  app/(auth)/_layout.tsx
  app/index.tsx
  constants/icon.ts
  package-lock.json
  package.json
Labels: Need Review

#164 Feature: Implement Auth context to manage authentication everywhere.
  app/(app)/ActionMenu/index.tsx
  app/(auth)/SignIn&SignOut/SetYourFingerPrint.tsx
  app/(auth)/SignIn&SignOut/SignInBlankForm.tsx
  app/(auth)/SignIn&SignOut/SignUpBlankForm.tsx
  app/(auth)/SignIn&SignOut/YourProfile.tsx
  app/(auth)/SignIn&SignOut/YourProfile/[email].tsx
  app/(auth)/_layout.tsx
  app/_layout.tsx
  components/UI/Input.tsx
  components/UI/SelectProfile.tsx
  components/UI/TakeActionModal.tsx
  ctx/AuthContext.tsx
  ctx/TakeActionModalContext.tsx
  package-lock.json
  package.json
Labels: Need Review

#167 Bug fix: Displayed logged in user profile Image
  app/(app)/ActionMenu/AllDoctorScreen.tsx
  app/(app)/ActionMenu/index.tsx
  app/(app)/Profile/EditProfile.tsx
  app/(app)/Profile/index.tsx
  app/(auth)/CreateNewPassword.tsx
  app/(auth)/ForgotPassword&Reset/index.tsx
  app/(auth)/SignIn&SignOut/YourProfile/[email].tsx
  components/DoctorComponent.tsx
  components/UI/SelectProfile.tsx
  components/UI/TabBar.tsx
  constants/Types.ts
  utils/LoggedInUser.ts
Labels: Feature, Need Review

#172 bg: Fix environment variable to resolve routing errors
  .env.example
  .gitignore
  app/(app)/Articles/[ArticleDetails].tsx
  app/(app)/Articles/index.tsx
  babel.config.js
  components/cards/ArticleCard.tsx
  lib/supabase.ts
  package-lock.json
  package.json
Labels: Need Review

#177 Add Facebook User Data Integration
  .env.example
  app.json
  app/(app)/ActionMenu/AllDoctorScreen.tsx
  app/(app)/ActionMenu/index.tsx
  app/(app)/Appointments/MessagingAppointment/Camera.tsx
  app/(app)/Appointments/MessagingAppointment/Playsound.tsx
  app/(app)/Profile/index.tsx
  app/(auth)/CreateNewPassword.tsx
  app/(auth)/SignIn&SignOut/LetsYouIn.tsx
  app/(auth)/SignIn&SignOut/YourProfile/[email].tsx
  app/_layout.tsx
  babel.config.js
  ctx/AuthContext.tsx
  lib/supabase.ts
  package-lock.json
Labels: Feature

#179 Fix: A fix for an issue in image loading on the home screen and user description
  app/(app)/ActionMenu/index.tsx
  app/(auth)/SignIn&SignOut/YourProfile/[email].tsx
  babel.config.js
  ctx/AuthContext.tsx
Labels: bug, Fix, Need Review

#159 Add logic to fetch and display individual doctor details from database
  app/(app)/ActionMenu/AllDoctorScreen.tsx
  app/(app)/ActionMenu/Booking/BookingAppointment.tsx
  app/(app)/ActionMenu/Booking/Doctor_details.tsx
  app/(app)/ActionMenu/Booking/EnterYourPin.tsx
  app/(app)/ActionMenu/Booking/Patient-details.tsx
  app/(app)/ActionMenu/Booking/Select-package.tsx
  app/(app)/ActionMenu/Booking/SelectPayment.tsx
  app/(app)/ActionMenu/Booking/_layout.tsx
  app/(app)/ActionMenu/Booking/reviewSummary.tsx
  app/(app)/ActionMenu/index.tsx
  app/(app)/index.tsx
  app/_layout.tsx
  components/DoctorComponent.tsx
  components/HeaderComponent.tsx
  components/PackagesContainer.tsx
  components/SelectHour.tsx
  components/UI/ChipsComponent.tsx
  components/UI/Date.tsx
  components/UI/DatePicker.tsx
  components/UI/DropDown.tsx
  components/UI/TextArea.tsx
Labels: Feature, Need Review

#181 Feature: Implement Bookmark and Filter Features in Medica App
  app/(app)/ActionMenu/index.tsx
  app/(app)/Articles/ArticleSeeAll.tsx
  app/(app)/Articles/BookMarkedArticles.tsx
  app/(app)/Articles/[ArticleDetails].tsx
  app/(app)/Articles/_layout.tsx
  app/(app)/Articles/index.tsx
  app/(app)/Profile/index.tsx
  app/(auth)/SignIn&SignOut/YourProfile/[email].tsx
  app/index.tsx
  components/FieldComponent.tsx
  components/cards/ArticleCard.tsx
  ctx/AuthContext.tsx
Labels: Feature, Need Review

#183 Add Functional Specialization Buttons
  app/(app)/ActionMenu/AllDoctorScreen.tsx
  app/(app)/ActionMenu/FavoriteDoctorScreen.tsx
  app/(app)/ActionMenu/index.tsx
  app/(app)/Appointments/ReschedualAppointment/rescheduleDate.tsx
  package-lock.json
  package.json
  tsconfig.json
Labels: Need Review
