Repository atlp-rwanda/matadors-rn-medica, pull requests merged in 2024-05, with the labels that each got.

#10 chore: setup readme file
  README.md
Labels: Chore

#15 Chore (setup project structure. Worked on colors, constants, and icons)
  app.json
  app/(app)/HomeScreen.tsx
  app/(app)/_layout.tsx
  app/(auth)/SignIn&SignOut/SetYourFingerPrint.tsx
  app/(auth)/_layout.tsx
  app/(tabs)/_layout.tsx
  app/(tabs)/index.tsx
  app/(tabs)/two.tsx
  app/_layout.tsx
  app/index.tsx
  assets/fonts/SpaceMono-Regular.ttf
  assets/fonts/Urbanist-Bold.ttf
  assets/fonts/Urbanist-Medium.ttf
  assets/fonts/Urbanist-Regular.ttf
  assets/fonts/Urbanist-SemiBold.ttf
  assets/icons/Arrow_Left.svg
  components/StyledText.tsx
  components/Themed.tsx
  components/UI/Header.tsx
  components/UI/icons.tsx
  components/useColorScheme.web.ts
  constants/Colors.ts
  constants/Typography.ts
  package-lock.json
  package.json
  utils/ResponsiveWidth.tsx
Labels: Need Rebase

#19 Chore: setup theme context
  app.json
  app/(auth)/SignIn&SignOut/SetYourFingerPrint.tsx
  app/_layout.tsx
  constants/Types.ts
  ctx/ThemeContext.tsx
  package-lock.json
  package.json
Labels: Chore

#17 Chore: Add GitHub Actions Workflows for Continuous Integration
  .github/workflows/pull_request.yml
  .github/workflows/push.yml
  components/__tests__/__snapshots__/StyledText-test.js.snap
  package-lock.json
  package.json
Labels: Need Review, Need Rebase

#16 Feature: add onboarding screens
  .gitignore
  app.json
  app/_layout.tsx
  app/onBoarding/FirstScreen.tsx
  app/onBoarding/SecondScreen.tsx
  app/onBoarding/ThirdScreen.tsx
  app/onBoarding/_layout.tsx
  components/OnBoarding/OnboardingComponent.tsx
  package.json
Labels: Fix, Need Review

#23 chore(github-actions): create update.yml and add code coverage config…
  .github/workflows/codecov.yml
  .github/workflows/update.yml
  .gitignore
  README.md
  app.json
  app/_layout.tsx
  app/index.tsx
  eas.json
  package-lock.json
  package.json
Labels: Need Review

#28 Feature: Signup and login screens
  app.json
  app/(auth)/SignIn&SignOut/LetsYouIn.tsx
  app/(auth)/SignIn&SignOut/SignInBlankForm.tsx
  app/(auth)/SignIn&SignOut/SignUpBlankForm.tsx
  app/_layout.tsx
  app/index.tsx
  assets/icons/AppleIcon.png
  assets/icons/FrameOne.png
  assets/icons/Google.png
  assets/icons/HeartPlus.png
  assets/icons/Lock.png
  assets/icons/Message.png
  assets/icons/OR.png
  assets/icons/continue.png
  assets/icons/facebook.png
  package-lock.json
  package.json
Labels: Need Review

#38 Feature: Forget Password and OTP verification
  app/(auth)/ForgotPassword&Reset/ForgotPassword.tsx
  app/(auth)/ForgotPassword&Reset/OTPform.tsx
  app/(auth)/SignIn&SignOut/LetsYouIn.tsx
  app/(auth)/SignIn&SignOut/SignInBlankForm.tsx
  app/(auth)/SignIn&SignOut/SignUpBlankForm.tsx
  app/(auth)/_layout.tsx
  app/index.tsx
  assets/images/ForgotPasswordImages/Chat.svg
  assets/images/ForgotPasswordImages/Message.svg
  assets/images/ForgotPasswordImages/forgotpassword.png
  assets/images/ForgotPasswordImages/forgotpassworddark.png
  components/OTPcomponents/countdownTimer.tsx
  components/UI/icons.tsx
  constants/Colors.ts
  package-lock.json
  package.json
Labels: Feature, Need Review

#42 Refactor: Implement Theme Context for Different Themes and organize routing
  SpashScreen/Splash.tsx
  app/(app)/ActionMenu/index.tsx
  app/(app)/Appointments/CancelAppointment/index.tsx
  app/(app)/Appointments/MessagingAppointment/index.tsx
  app/(app)/Appointments/ReaschedualAppointment/index.tsx
  app/(app)/Appointments/Review/index.tsx
  app/(app)/Appointments/VideoCallAppointment/index.tsx
  app/(app)/Appointments/VoiceCallAppointment/index.tsx
  app/(app)/Articles/index.tsx
  app/(app)/Booking/index.tsx
  app/(app)/History/MessageHistory/index.tsx
  app/(app)/History/VideoCallHistory/index.tsx
  app/(app)/History/VoiceCallHistory/index.tsx
  app/(app)/HomeScreen.tsx
  app/(app)/SearchAndFilter/index.tsx
  app/(app)/Settings/index.tsx
  app/(app)/_layout.tsx
  app/(auth)/CreateNewPassword.tsx
  app/(auth)/ForgotPassword&Reset/ForgotPassword.tsx
  app/(auth)/ForgotPassword&Reset/OTPform.tsx
  app/(auth)/SignIn&SignOut/Create-NewPin.tsx
  app/(auth)/SignIn&SignOut/LetsYouIn.tsx
  app/(auth)/SignIn&SignOut/SetYourFingerPrint.tsx
  app/(auth)/SignIn&SignOut/SignInBlankForm.tsx
  app/(auth)/SignIn&SignOut/SignUpBlankForm.tsx
  app/(auth)/SignIn&SignOut/YourProfile.tsx
  app/(auth)/_layout.tsx
  app/Onboading/OnboardingScreen.tsx
  app/_layout.tsx
  app/index.tsx
  app/onBoarding/FirstScreen.tsx
  app/onBoarding/SecondScreen.tsx
  app/onBoarding/ThirdScreen.tsx
  app/onBoarding/_layout.tsx
  components/OnBoarding/OnboardingComponent.tsx
  components/UI/Icons.tsx
Labels: Need Review

#47 Feature: Display appointment notifications
  app/(app)/ActionMenu/HomeScreen.tsx
  app/(app)/ActionMenu/NotificationScreen.tsx
  app/(app)/_layout.tsx
  assets/icons/calendar1.ts
  assets/icons/calendar2.ts
  assets/icons/close.ts
  assets/icons/doctor.ts
  assets/icons/heart.ts
  assets/icons/iconMapping.ts
  assets/icons/service.ts
  assets/icons/star.ts
  assets/icons/wallet.ts
  assets/images/Doctor1.png
  assets/images/Doctor2.png
  assets/images/Doctor3.png
  assets/images/Doctor4.png
  assets/images/Doctor5.png
  components/Notficationtab.tsx
  data.json
  package-lock.json
  package.json
Labels: Feature, Need Review

#46 Feature: Display Individual Doctor's Information and the review pages
  app/(app)/ActionMenu/HomeScreen.tsx
  app/(app)/Booking/DoctorRatingAndReview.tsx
  app/(app)/Booking/Doctor_details.tsx
  app/(app)/_layout.tsx
  app/index.tsx
  assets/images/jenny_watson.png
  components/ReviewerCardComponent.tsx
  components/UI/icons/backArrow.ts
  components/UI/icons/blackHeart.ts
  components/UI/icons/blueHeart.ts
  components/UI/icons/blueMessage.ts
  components/UI/icons/bluePeople.ts
  components/UI/icons/circleWithDots.ts
  components/UI/icons/halfTransparentStart.ts
  components/UI/icons/star.ts
  components/UI/icons/statistics.ts
  constants/Colors.ts
  package-lock.json
Labels: Feature, Need Review

#51 Feature: Add Appointment Booking Screen with Calendar and Time Selection
  app/(app)/Booking/BookingAppointment.tsx
  app/(app)/Booking/Doctor_details.tsx
  app/(app)/_layout.tsx
  package-lock.json
  package.json
Labels: Need Review

#49 Feature: Appointment Review Summary
  app/(app)/Booking/_layout.tsx
  app/(app)/Booking/reviewSummary.tsx
  app/_layout.tsx
  assets/images/BookingImages/Frame.svg
  assets/images/BookingImages/doctor.jpg
  assets/images/BookingImages/doctor.png
  assets/images/BookingImages/mastercard.svg
  assets/images/BookingImages/mastercard2.svg
  assets/images/BookingImages/mastercarddark.png
  assets/images/BookingImages/mastercardwhite.png
  components/UI/Icons.tsx
Labels: Feature, Need Review

#43 Feature: Select Payment Method Screen
  app/(app)/Booking/SelectPayment.tsx
  app/(app)/Booking/_layout.tsx
  app/(app)/Booking/index.tsx
  app/(app)/_layout.tsx
  app/Onboading/OnboardingScreen.tsx
  app/index.tsx
  app/onBoarding/FirstScreen.tsx
  app/onBoarding/ThirdScreen.tsx
  assets/images/apple_icon.png
  assets/images/google_icon.png
  assets/images/paypal_icon.png
  assets/images/select_btn.png
  components/UI/Header.tsx
  components/UI/Icons.tsx
  components/UI/PaymentChooseContainer/Index.tsx
  components/UI/PaymentChooseContainer/PaymentChooseInputCard.tsx
  constants/PaymentMethods.ts
  constants/Types.ts
  package-lock.json
Labels: Need Review

#54 ft(Booking): Add New Card Screen
  app/(app)/Booking/AddNewCard.tsx
  assets/icons/Calendar.png
  assets/icons/CalendarWhite.png
  assets/icons/Mocard.png
  assets/icons/Scan.png
  package-lock.json
  package.json
Labels: Need Review

#44 Feature: Select Package& Patient Details(Reschedule-Appointment)6.39-40
  app/(app)/ActionMenu/Booking/BookingAppointment.tsx
  app/(app)/ActionMenu/Booking/EnterYourPin.tsx
  app/(app)/ActionMenu/Booking/Patient-details.tsx
  app/(app)/ActionMenu/Booking/Select-package.tsx
  app/(app)/ActionMenu/Booking/SelectPayment.tsx
  app/(app)/ActionMenu/Booking/_layout.tsx
  app/(app)/ActionMenu/Booking/reviewSummary.tsx
  app/(app)/Appointments/Select-package.tsx
  app/(app)/index.tsx
  assets/images/AutoLayout.png
  assets/images/TimeCircle.png
  assets/images/VideoCall.png
  assets/images/VoiceCall.png
  package-lock.json
Labels: Need Review

#60 ft(messaging): Add messaging appointment and chats
  app/(app)/Appointments/MessagingAppointment/AppointmentMessaging.tsx
  app/(app)/Appointments/MessagingAppointment/ChatMessaging.tsx
  app/(app)/Appointments/MessagingAppointment/_layout.tsx
  app/(app)/Appointments/_layout.tsx
  app/(app)/index.tsx
  components/DoctorCard.tsx
  components/UI/icons/attachIcon.ts
  components/UI/icons/blueMessage.ts
  components/UI/icons/cameraIcon.ts
  components/UI/icons/doubleTickIcon.ts
  components/UI/icons/filterIcon.ts
  components/UI/icons/flashLight.ts
  components/UI/icons/imojiIcon.ts
  components/UI/icons/voiceIcon.ts
Labels: Need Review

#57 Implement Category-based Filtering and Display for Favorite Doctors
  app/(app)/ActionMenu/FavoriteDoctorScreen.tsx
  app/(app)/ActionMenu/_layout.tsx
  app/(app)/ActionMenu/index.tsx
  app/doctors.json
  app/index.tsx
  assets/icons/Search&FilterIcons/filter.ts
  assets/icons/Search&FilterIcons/inputSearch.ts
  assets/icons/blueHeart.ts
  assets/icons/left.ts
  assets/icons/more.ts
  assets/icons/search.ts
  assets/icons/star.ts
  assets/images/Doctors/doctor1.png
  assets/images/Doctors/doctor2.png
  assets/images/Doctors/doctor3.png
  assets/images/Doctors/doctor4.png
  assets/images/Doctors/doctor5.png
  components/DoctorComponent.tsx
  components/HeaderComponent.tsx
  components/SearchComponent.tsx
  package-lock.json
  package.json
  tsconfig.json
Labels: Need Review

#71 Feature: Add Scheduled Appointment Components
  app/(app)/Appointments/_layout.tsx
  app/(app)/Appointments/index.tsx
  app/(app)/index.tsx
  assets/icons/MoreCircleSvg.ts
  assets/icons/SearchSvg.ts
  assets/images/DefaultLogo.png
  assets/images/Dr jenny.png
  assets/images/Dr maria.png
  assets/images/Messaging.png
Labels: Need Review

#63 Feature(Appointment): Voice Call Appointment
  app/(app)/Appointments/Review/ReviewScreen.tsx
  app/(app)/Appointments/VoiceCallAppointment/MyAppointmentVoiceCall.tsx
  app/(app)/Appointments/VoiceCallAppointment/SessionEnded.tsx
  app/(app)/Appointments/VoiceCallAppointment/VoiceCallRinging.tsx
  app/(app)/Appointments/_layout.tsx
  app/(app)/Appointments/index.tsx
  app/(app)/_layout.tsx
  app/(app)/index.tsx
  assets/icons/HorizantalLine.ts
  assets/icons/HorizontalLine.svg
  assets/icons/LeftBlackArrow.ts
  assets/images/Background.png
  assets/images/Drake.png
  assets/images/Jenny.png
  components/Icons/Icons.ts
  components/UI/icons/MyAppointmentVoiceCall.tsx
  components/UI/icons/SessionEnded.tsx
  components/UI/icons/VoiceCallRinging.tsx
  components/UI/icons/WhiteMenuCircle.ts
  package-lock.json
Labels: Need Review

#68 Feature: Settings Section Screens
  app.json
  app/(app)/Profile/EditProfile.tsx
  app/(app)/Profile/HelpCenter.tsx
  app/(app)/Profile/InviteFriends.tsx
  app/(app)/Profile/Languages.tsx
  app/(app)/Profile/Notification.tsx
  app/(app)/Profile/Payment.tsx
  app/(app)/Profile/Security.tsx
  app/(app)/Profile/_layout.tsx
  app/(app)/Profile/index.tsx
  app/(app)/_layout.tsx
  app/(app)/index.tsx
  app/(auth)/SignIn&SignOut/SetYourFingerPrint.tsx
  app/(auth)/_layout.tsx
  app/index.tsx
  assets/icons/EditBlueIcon.ts
  assets/icons/EmptyImageContainer.ts
  assets/icons/LightDivider.ts
  assets/icons/Logo.ts
  assets/icons/Profile/Icons.ts
  assets/icons/ThreeDotCircle.ts
  assets/images/Friends/Ellipse-1.png
  assets/images/Friends/Ellipse-2.png
  assets/images/Friends/Ellipse-3.png
  assets/images/Friends/Ellipse-4.png
  assets/images/Friends/Ellipse-5.png
  assets/images/Friends/Ellipse-6.png
  assets/images/Friends/Ellipse-7.png
  assets/images/Friends/Ellipse-8.png
  assets/images/Friends/Ellipse.png
  components/Profile/FriendsListing.tsx
  components/Profile/LanguageListing.tsx
  components/Profile/LanguagesList.tsx
  components/Profile/OptionListing.tsx
  components/Profile/SelectedPaymentCardListing.tsx
  components/Profile/SwitchNotificationListing.tsx
  components/UI/Header.tsx
  components/UI/Input.tsx
  components/UI/OutlineButton.tsx
  constants/Languages.ts
  constants/Types.ts
  constants/Typography.ts
  data.json
  package-lock.json
  package.json
Labels: Need Review

#67 Feature-Reschedule-Appointment
  app/(app)/Appointments/ReschedualAppointment/rescheduleDate.tsx
  app/(app)/Appointments/ReschedualAppointment/selectreason.tsx
  app/(app)/Appointments/_layout.tsx
  app/(app)/Appointments/index.tsx
  app/(app)/_layout.tsx
  assets/images/calendarmodal.png
  package-lock.json
  package.json
Labels: Need Review

#70 Enhance Search Functionality with Result Count and No Results Feedback
  README.md
  app/(app)/ActionMenu/FavoriteDoctorScreen.tsx
  app/(app)/Appointments/VoiceCallAppointment/SessionEnded.tsx
  app/doctors.json
  assets/icons/Defaulticon.ts
  assets/images/Doctors/notFound.png
  components/FoundDoctorCount.tsx
  components/NofoundComponent.tsx
  components/SearchComponent.tsx
  package-lock.json
  package.json
Labels: Need Review

#65 Feature : Implement Chat Features in Medica App
  app.json
  app/(app)/ActionMenu/Booking/Doctor_details.tsx
  app/(app)/ActionMenu/Booking/Select-package.tsx
  app/(app)/Appointments/MessagingAppointment/AttachComponent.tsx
  app/(app)/Appointments/MessagingAppointment/Camera.tsx
  app/(app)/Appointments/MessagingAppointment/ChatMessaging.tsx
  app/(app)/Appointments/MessagingAppointment/Menu.tsx
  app/(app)/Appointments/MessagingAppointment/_layout.tsx
  app/(app)/Appointments/MessagingAppointment/index.tsx
  app/(app)/Appointments/index.tsx
  assets/images/audioImg.png
  assets/images/documentImg.png
  assets/images/garellyImg.png
  assets/images/leftFoot.png
  assets/images/rigthFoot.png
  components/UI/icons/deleteIcon.ts
  components/UI/icons/downloadIcon.ts
  package-lock.json
  package.json
Labels: Need Review

#73 Feature(Appointment): Add Post-Call Review Screen for Patient Feedback
  app.json
  app/(app)/Appointments/Review/Popup.tsx
  app/(app)/Appointments/Review/ReviewBlankform.tsx
  app/(app)/Appointments/_layout.tsx
  app/(app)/index.tsx
  assets/icons/DivLine.ts
  assets/icons/Success.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: Need Review

#75 Feature: remove doctors from favorite
  app/(app)/ActionMenu/FavoriteDoctorScreen.tsx
  components/DoctorComponent.tsx
  components/Removebtn.tsx
  components/RemovefavoritePopup.tsx
  data.json
Labels: Need Review

#77 Feat: Add Functionality to Implement Search Filters by Category and Rating
  app/(app)/ActionMenu/FavoriteDoctorScreen.tsx
  assets/icons/blueStar.ts
  assets/icons/whiteStar.ts
  components/FilterSearchComponent.tsx
  components/Ratebtn.tsx
  components/SearchComponent.tsx
Labels: Feature, Need Review

#85 Feature: FAQS & Contact Us screens
  README.md
  app.json
  app/(app)/ActionMenu/Booking/Doctor_details.tsx
  app/(app)/ActionMenu/Booking/Patient-details.tsx
  app/(app)/ActionMenu/Booking/Select-package.tsx
  app/(app)/ActionMenu/Booking/SelectPayment.tsx
  app/(app)/ActionMenu/Booking/_layout.tsx
  app/(app)/ActionMenu/_layout.tsx
  app/(app)/Profile/HelpCenter.tsx
  app/(app)/Profile/HelpCenter/ContactUs.tsx
  app/(app)/Profile/HelpCenter/FAQ.tsx
  app/(app)/Profile/HelpCenter/_layout.tsx
  app/_layout.tsx
  assets/icons/Profile/Icons.ts
  components/Profile/ContactsListing.tsx
  components/UI/Accordion.tsx
  components/UI/HorizontalSeparator.tsx
  components/UI/Search.tsx
  components/UI/Tags/Tag.tsx
  components/UI/Tags/index.tsx
  package-lock.json
  package.json
Labels: Feature, Need Review

#88 Feature: Add Scheduled Appointments Components
  app/(app)/Appointments/index.tsx
  app/Appointments.json
  components/AppointmentDoctorsCards.tsx
  components/AppointmentStatus.tsx
  package-lock.json
Labels: Feature, Need Review

#89 Add History Screen for Viewing Messaging, Voice Call, and Video Call History
  app/(app)/History/MessageHistory/index.tsx
  app/(app)/History/VoiceCallHistory/index.tsx
  app/(app)/History/_layout.tsx
  app/(app)/History/history.json
  assets/icons/Right_arrow.ts
  components/CardComponent.tsx
  components/Historyheader.tsx
  components/MessageComponent.tsx
  components/SearchComponent.tsx
Labels: Need Review

#91 Feature: Implement History Feature for Consultation Methods in Medica App
  app/(app)/ActionMenu/Booking/_layout.tsx
  app/(app)/History/CardComponent.tsx
  app/(app)/History/HistoryMenu.tsx
  app/(app)/History/MessageHistory/Chats.tsx
  app/(app)/History/MessageHistory/Menu.tsx
  app/(app)/History/VideoCallHistory/[id].tsx
  app/(app)/History/VideoCallHistory/index.tsx
  app/(app)/History/VoiceCallHistory/[id].tsx
  app/(app)/History/VoiceCallHistory/index.tsx
  app/(app)/History/_layout.tsx
  app/(app)/History/index.tsx
  app/(app)/_layout.tsx
  components/CardComponent.tsx
  components/UI/Button.tsx
  components/UI/icons/deleteIcon.ts
  components/UI/icons/rigthIcon.ts
  package-lock.json
  package.json
Labels: Need Review

#90 Feature: Cancel appointment
  app/(app)/Appointments/CancelAppointment/cancelreason.tsx
  app/(app)/Appointments/MessagingAppointment/ChatMessaging.tsx
  app/(app)/Appointments/MessagingAppointment/index.tsx
  app/(app)/Appointments/ReschedualAppointment/Selectreason.tsx
  app/(app)/Appointments/Review/Popup.tsx
  app/(app)/Appointments/Review/ReviewBlankform.tsx
  app/(app)/Appointments/VoiceCallAppointment/MyAppointmentVoiceCall.tsx
  app/(app)/Appointments/VoiceCallAppointment/index.tsx
  app/(app)/Appointments/_layout.tsx
  app/(app)/Appointments/index.tsx
  app/Appointments.json
  assets/images/cancelimg.png
  components/AppointmentDoctorsCards.tsx
  components/UI/icons/callIcon.ts
  components/UI/icons/videoCallIcon.ts
  components/cancelappointmentmodal.tsx
  package-lock.json
Labels: Feature, Need Review

#93 feat: all articles screens added
  app/(app)/Articles/ArticleDetails.tsx
  app/(app)/Articles/ArticleSeeAll.tsx
  app/(app)/Articles/_layout.tsx
  app/(app)/Articles/index.tsx
  assets/images/Arrow.png
  assets/images/Image1.png
  assets/images/Image2.png
  assets/images/Image4.png
  assets/images/Notify.png
  assets/images/circledots.png
  assets/images/search1.png
  assets/images/send.png
  components/FieldComponent.tsx
  components/cards/ArticleCard.tsx
  constants/Articles.ts
  package-lock.json
Labels: Feature, Need Review

#101 Fix :Fix and Enhance UI for History Screen
  app.json
  app/(app)/Appointments/VideoCallAppointment/VideoCallSessionEnded.tsx
  app/(app)/History/CardComponent.tsx
  app/(app)/History/HistoryMenu.tsx
  app/(app)/History/MessageHistory/Chats.tsx
  app/(app)/History/MessageHistory/Menu.tsx
  app/(app)/History/VideoCallHistory/VideoPlayer.tsx
  app/(app)/History/VideoCallHistory/[id].tsx
  app/(app)/History/VoiceCallHistory/[id].tsx
  app/(app)/History/VoiceCallHistory/index.tsx
  app/(app)/History/_layout.tsx
  app/(app)/History/index.tsx
  app/(app)/_layout.tsx
  app/(auth)/SignIn&SignOut/SetYourFingerPrint.tsx
  app/Onboading/OnboardingScreen.tsx
  assets/images/videoCallHistoryBgImage.png
  components/CardComponent.tsx
  components/Historyheader.tsx
  components/MessageComponent.tsx
  components/UI/icons/audioWave.ts
  components/UI/icons/cameraIcon.ts
  components/UI/icons/circleWithDots.ts
  components/UI/icons/deleteIcon.ts
  components/UI/icons/downloadIcon.ts
  components/UI/icons/filterIcon.ts
  components/UI/icons/playBtn.ts
  constants/icon.ts
  package-lock.json
  package.json
Labels: Need Review

#115 Fix: HomeScreen UI improvements and dark theme Enhancement
  app/(app)/ActionMenu/index.tsx
  components/UI/icons/blackHeart.ts
  package-lock.json
  package.json
Labels: Fix

#105 Enhance Notification screen UI and Dark theme
  app/(app)/ActionMenu/NotificationScreen.tsx
  app/(auth)/SignIn&SignOut/YourProfile.tsx
Labels: Need Review

#119 feat: Setting up the dark theme for some screens.
  app/(app)/ActionMenu/Booking/Patient-details.tsx
  app/(app)/ActionMenu/Booking/Select-package.tsx
  app/(app)/Articles/ArticleDetails.tsx
  app/(app)/Articles/ArticleSeeAll.tsx
  app/(app)/Articles/index.tsx
  app/(auth)/SignIn&SignOut/Create-NewPin.tsx
  app/_layout.tsx
  components/FieldComponent.tsx
  components/cards/ArticleCard.tsx
Labels: Need Review

#116 Fixes and Enhancements to Doctor Details Screen
  app/(app)/ActionMenu/Booking/Doctor_details.tsx
  app/(app)/ActionMenu/Booking/SelectPayment.tsx
  app/(app)/ActionMenu/Booking/_layout.tsx
  app/(auth)/SignIn&SignOut/LetsYouIn.tsx
  app/(auth)/SignIn&SignOut/SignInBlankForm.tsx
  app/(auth)/SignIn&SignOut/SignUpBlankForm.tsx
  assets/images/Booking/Card.tsx
  assets/images/Booking/card.svg
  assets/images/Charly.png
  components/Icons/Icons.ts
  components/Icons/Scanner.png
  components/UI/Header.tsx
  components/UI/icons/WhiteThreeDots.ts
  package-lock.json
  package.json
Labels: Need Review
